### ISSUE TITLE
Can't build with Clang 14.0.6

### ISSUE THREAD

**Issue by Nitr4m12** [zeldamods/oead#23]
I was trying to build oead using Clang (v. 14.0.6), but it always throws out this error:
```
oead/src/yaz0.cpp:168:20: error: invalid value '0'; must be positive
[build] #pragma GCC unroll 0
[build]                    ^
[build] 1 error generated.
```
Bulding with GCC does work though, so it can be built using that.

**Comment by leoetlino** [comment]
Should probably add an ifdef to only use that pragma for GCC. Or just remove it if GCC's codegen was fixed

**Comment by MonsterDruide1** [comment]
Just a late follow-up on this, because I just saw that this was discussed in here as well: This was actually an issue with `clang` parsing, the specs also allow `0` as value for unroll, which was incorrectly implemented in `clang` since ... forever.

https://github.com/llvm/llvm-project/issues/88624
